-- CreateEnum
CREATE TYPE "topic_icon" AS ENUM ('DEFAULT', 'ALIGN_LEFT', 'BOT', 'BRACES', 'CPU', 'DATABASE', 'DATABASE_ZAP', 'ETHERNET_PORT', 'FILE_TEXT', 'GAMEPAD_2', 'GLOBE', 'LAYERS', 'LIST_CHECKS', 'MICROCHIP', 'MONITOR', 'NETWORK', 'SMARTPHONE');

-- AlterTable
ALTER TABLE "topics" ADD COLUMN     "icon" "topic_icon" NOT NULL DEFAULT 'DEFAULT';
